### ISSUE TITLE
Incorrect project name in ckeditor.info

### ISSUE THREAD

**Issue by GreenReaper** [d6lts/ckeditor#1]
The project name of this project is set to "projectname" when it seems like it should be "ckeditor" - this causes it to not show up correctly on Available updates, until it is reset. The change was made in https://github.com/d6lts/ckeditor/commit/e0491dfe9f05361c80899b62a3bc07159552c524

**Comment by dsnopek** [comment]
This is a mistake I made during release. It'll get fixed in the next release.

**Comment by dsnopek** [comment]
I just made a new release (6.x-1.18) which fixes this
